In [1]:
import numpy as np

In [ ]:
arr = [1,2,3,4,5]
np.array(arr)

array([1, 2, 3, 4, 5])

In [ ]:
mat = [
       [1,2,3],
       [4,5,6],
       [7,8,9]
]
mat2 =np.array(mat)
print(mat2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#arange
#arange(start,end,*step,*dtype)
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(0,11,2,float)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [ ]:
np.arange(0,16.0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [ ]:
#zeros
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#linspace
np.linspace(1,11,3)

array([ 1.,  6., 11.])

In [ ]:
np.linspace(1,11,25)

array([ 1.        ,  1.41666667,  1.83333333,  2.25      ,  2.66666667,
        3.08333333,  3.5       ,  3.91666667,  4.33333333,  4.75      ,
        5.16666667,  5.58333333,  6.        ,  6.41666667,  6.83333333,
        7.25      ,  7.66666667,  8.08333333,  8.5       ,  8.91666667,
        9.33333333,  9.75      , 10.16666667, 10.58333333, 11.        ])

In [ ]:
#eye
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
#random
#rand
np.random.rand(4)

array([0.50441438, 0.32485696, 0.37653209, 0.07515118])

In [ ]:
np.random.rand(10)

array([0.09424991, 0.12168865, 0.49596428, 0.84998467, 0.60342199,
       0.6378065 , 0.2828853 , 0.79345159, 0.97527285, 0.32187971])

In [ ]:
#randn
np.random.randn(4)

array([-0.76581459,  0.53178208,  2.60823632, -0.44291296])

In [ ]:
np.random.randn(7)

array([ 0.2118076 ,  0.54659172, -1.97092613,  0.11680774,  1.08151634,
        0.91399656,  0.098835  ])

In [ ]:
#randint
np.random.randint(1,6)

2

In [ ]:
np.random.randint(1,6,5)

array([1, 2, 3, 2, 4])

In [ ]:
np.random.randint(1,100,20)

array([13, 21, 48, 22, 90,  1, 79, 16, 92, 18, 55, 46, 51, 30, 36, 57, 34,
       14, 67, 75])

In [ ]:
arr = np.arange(25)

In [ ]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [ ]:
ran_arr = np.random.randint(0,50,10)
print(ran_arr)

[34 30 12 18 31  7 32  0 27 26]


In [ ]:
#size
arr.size

25

In [ ]:
ran_arr.size

10

In [ ]:
#max
arr.max()

24

In [ ]:
ran_arr.max()

34

In [ ]:
#min
arr.min()

0

In [ ]:
ran_arr.min()

0

In [ ]:
#argmax
arr.argmax()

24

In [ ]:
ran_arr.argmax()

0

In [ ]:
#argmin
arr.argmin()

0

In [ ]:
ran_arr.argmin()

7

In [ ]:
#shape
arr.shape

(25,)

In [ ]:
mat2.shape

(3, 3)

In [ ]:
#reshape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

In [ ]:
#dtype
arr.dtype

dtype('int64')

In [ ]:
mylist = np.array([1.,2.,3.])
print(mylist)

[1. 2. 3.]


In [ ]:
mylist.dtype

dtype('float64')

In [ ]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#index
a[5]

5

In [ ]:
a[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
a[2:4]

array([2, 3])

In [ ]:
#broadcasting
a[:5] = 100
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#slice
s = a[:5]
s

array([0, 1, 2, 3, 4])

In [ ]:
s[:] = 99
s

array([99, 99, 99, 99, 99])

In [ ]:
a

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
#copy
s = a.copy()
s

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
s = a[:5].copy()
s

array([99, 99, 99, 99, 99])

In [ ]:
s[:] = 100
s

array([100, 100, 100, 100, 100])

In [ ]:
a

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
#index of 2D
b = np.array([
     [1,2,3],
     [4,5,6],
     [7,8,9]

    ])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b[1]

array([4, 5, 6])

In [ ]:
b[1][1]

5

In [ ]:
b[1,1]

5

In [ ]:
#slicing of 2D
b[1:,:]


array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
b[1:,1:]

array([[5, 6],
       [8, 9]])

In [ ]:
b[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
#selection
arr = np.arange(0,6)
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr>4

array([False, False, False, False, False,  True])

In [ ]:
arr[arr>4]

array([5])

In [ ]:
arr[arr==4]

array([4])

In [ ]:
arr[arr==6]

array([], dtype=int64)

In [ ]:
#operation
c = np.arange(1,11)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
c+c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
c*c

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
b*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
c/c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
d = np.arange(0,11)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
d/d

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/d

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [ ]:
c**3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [ ]:
#universal
#square root
arr = np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [ ]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [ ]:
#exponential
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [ ]:
#log
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [ ]:
#max
np.max(arr)

5